#pragma once

#include <bitset>

#include "../utils/Utils.h"

class LocalPlayer : public Actor {
public:
	virtual void resolveDeathLoot(int, __int64 ActorDamageSource);
	virtual void Function370();
	virtual void setSleeping(bool);
	virtual void setSprinting(bool);
	virtual void playAmbientSound(void);
	virtual __int64 getAmbientSound(void);
	virtual __int64 getHurtSound(void);
	virtual __int64 getDeathSound(void);
	virtual __int64 getAmbientSoundPostponeTicks(void);
	virtual __int64 getAmbientSoundPostponeTicksRange(void);
	virtual __int64 getItemInHandIcon(ItemStack*, int);
	virtual float getSpeed(void);
	virtual void setSpeed(float);
	virtual float getJumpPower(void);
	virtual __int64 hurtEffects(__int64 ActorDamageSource, int, bool, bool);
	virtual __int64 getMeleeWeaponDamageBonus(Actor*);
	virtual __int64 getMeleeKnockbackBonus(void);
	virtual void travel(__int64* IMobMovementProxy, float, float, float);
	virtual void travel(float, float, float);
	virtual void applyFinalFriction(float, bool);
	virtual void updateWalkAnim(void);
	virtual void aiStep(__int64 IMobMovementProxy);
	virtual void aiStep(void);
	virtual void pushActors(void);
	virtual void lookAt(Actor*, float, float);
	virtual bool isLookingAtAnEntity(void);
	virtual bool checkSpawnRules(bool);
	virtual bool checkSpawnObstruction(void);
	virtual float getAttackAnim(float);
	virtual __int64 getItemUseDuration(void);
	virtual float getItemUseStartupProgress(void);
	virtual float getItemUseIntervalProgress(void);
	virtual __int64 getItemuseIntervalAxis(void);
	virtual __int64 getTimeAlongSwing(void);
	virtual void Function403();
	virtual float getMaxHeadXRot(void);
	virtual Actor* getLastHurtByMob(void);
	virtual void setLastHurtByMob(Actor*);
	virtual Actor* getLastHurtByPlayer(void);
	virtual void setLastHurtByPlayer(Player*);
	virtual Actor* getLastHurtMob(void);
	virtual void setLastHurtMob(Actor*);
	virtual void Function411();
	virtual void doHurtTarget(Actor*);
	virtual void leaveCaravan(void);
	virtual void joinCaravan(Actor*);
	virtual bool hasCaravanTail(void);
	virtual Actor* getCaravanHead(void);
	virtual __int64 getArmorValue(void);
	virtual __int64 getArmorCoverPercentage(void);
	virtual void hurtArmor(__int64 ActorDamageSource, int, std::bitset<4> const&);
	virtual void hurtArmor(__int64 ActorDamageSource, int);
	virtual void hurtArmorSlot(__int64 ActorDamageSource, int, int ArmorSlot);
	virtual void setDamagedArmor(int ArmorSlot, ItemStack*);
	virtual void sendArmorDamage(std::bitset<4> const&);
	virtual void sendArmor(std::bitset<4> const&);
	virtual bool containerChanged(int);
	virtual void updateEquipment(void);
	virtual void clearEquipment(void);
	virtual std::vector<ItemStack*> getAllArmor(void);
	virtual __int64 getAllArmorID(void);
	virtual ItemStack* getAllHand(void);
	virtual std::vector<ItemStack*> getAllEquipment(void);
	virtual __int64 getArmorTypeHash(void);
	virtual void dropEquipmentOnDeath(void);
	virtual void dropEquipmentOnDeath(__int64 ActorDamageSource, int);
	virtual void clearVanishEnchantedItemsOnDeath(void);
	virtual void sendInventory(bool);
	virtual void getDamageAfterMagicAbsorb(__int64 ActorDamageSource, int);
	virtual void createAIGoals(void);
	virtual void Function440();
	virtual void setItemSlot(int EquipmentSlot, ItemStack*);
	virtual void setTransitioningSitting(bool);
	virtual void attackAnimation(Actor*, float);
	virtual void Function444();
	virtual void Function445();
	virtual void Function446();
	virtual void ascendLadder(void);
	virtual void ascendScaffolding(void);
	virtual void _ascendScaffolding(void);
	virtual void descendScaffolding(void);
	virtual bool canAscendCurrentBlockByJumping(void);
	virtual void dropContainer(void);
	virtual void initBodyControl(void);
	virtual void jumpFromGround(__int64* IMobMovementProxy);
	virtual void jumpFromGround(void);
	virtual void Function456();
	virtual void newServerAiStep(void);
	virtual void Function448();
	virtual __int64 getDamageAfterEnchantReduction(__int64 ActorDamageSource, int);
	virtual __int64 getDamageAfterArmorAbsorb(__int64 ActorDamageSource, int);
	virtual void dropBags(void);
	virtual void tickDeath(void);
	virtual void updateGliding(void);
	virtual void Function454();
	virtual void prepareRegion(class ChunkSource*);
	virtual void destroyRegion(void);
	virtual void suspendRegion(void);
	virtual void resendAllChunks(void);
	virtual void _fireWillChangeDimension(void);
	virtual void _fireDimensionChanged(void);
	virtual void changeDimensionWithCredits(int);
	virtual void tickWorld(__int64 Tick);
	virtual void Function463();
	virtual std::vector<__int64, __int64> getTickingOffsets(void);
	virtual void moveView(void);
	virtual void setName(std::basic_string<char, std::char_traits<char>, std::allocator<char>> const&);
	virtual void checkMovementStats(Vec3*);
	virtual void Function468();
	virtual void Function469();
	virtual void respawn(void);
	virtual void Function471();
	virtual void resetPos(bool);
	virtual void Function473();
	virtual bool hasResource(int);
	virtual void completeUsingItem(void);
	virtual void setPermissions(int CommandPermissionLevel);
	virtual void startDestroying(void);
	virtual void stopDestroying(void);
	virtual void Function479();
	virtual void Function480();
	virtual void openTrading(__int64 ActorUniqueID, bool);
	virtual bool canOpenContainerScreen(void);
	virtual void Function483();
	virtual void Function484();
	virtual void openInventory(void);
	virtual void Function486();
	virtual void Function487();
	virtual void displayTextObjectMessage(TextHolder*);
	virtual void displayTextObjectWhisperMessage(TextHolder*);
	virtual void displayWhisperMessage(TextHolder*);
	virtual void startSleepInBed(Vec3_i*);
	virtual void stopSleepInBed(bool, bool);
	virtual bool canStartSleepInBed(void);
	virtual __int64 getSleepTimer(void);
	virtual __int64 getPreviousTickSleepTimer(void);
	virtual void Function496();
	virtual void Function497();
	virtual bool isHostingPlayer(void);
	virtual bool isLoading(void);
	virtual bool isPlayerInitialized(void);
	virtual void Function501();
	virtual void registerTrackedBoss(__int64 ActorUniqueID);
	virtual void unRegisterTrackedBoss(__int64 ActorUniqueID);
	virtual void setPlayerGameType(int GameType);
	virtual void initHUDContainerManager(void);
	virtual void _crit(Actor*);
	virtual __int64 getEventing(void);
	virtual void Function508();
	virtual void sendEventPacket(class Packet* EventPacket);
	virtual void addExperience(int);
	virtual void addLevels(int);
	virtual void setContainerData(__int64 IContainerManager, int, int);
	virtual void slotChanged(__int64 IContainerManager, __int64 Container, int, ItemStack*, ItemStack*, bool);
	virtual void inventoryChanged(__int64 Container, int, ItemStack*, ItemStack*, bool);
	virtual void refreshContainer(__int64 IContainerManager);
	virtual void deleteContainerManager(void);
	virtual void setFieldOfViewModifier(float);
	virtual bool is2DPositionRelevant(int Dimension, Vec3_i* BlockPos);
	virtual bool isEntityRelevant(Actor*);
	virtual bool isTeacher(void);
	virtual void onSuspension(void);
	virtual void onLinkedSlotsChanged(void);
	virtual void startCooldown(class Item*);
	virtual int getItemCooldownLeft(std::basic_string<char, std::char_traits<char>, std::allocator<char>> const&);
	virtual bool isItemInCooldown(std::basic_string<char, std::char_traits<char>, std::allocator<char>> const&);
	virtual void endInventoryTransaction(__int64 InventoryTransaction);
	virtual void sendComplexInventoryTransaction(std::unique_ptr<class ComplexInventoryTransaction, std::default_delete<class ComplexInventoryTransaction>>);
	virtual void sendNetworkPacket(Packet*);
	virtual __int64 getPlayerEventCoordinator(void);
	virtual __int64 getMoveInputHandler(void);
	virtual __int64 getInputMode(void);
	virtual int getPlayMode(void);
	virtual void reportMovementTelemetry(__int64 MovementEventType);
	virtual void onMovePlayerPacketNormal(Vec3*, Vec2*, float);

	inline void printToChat(std::string message) {
		TextHolder t(message);
		this->displayTextObjectMessage(&t);
	}
};
